# Generated by Django 5.0.3 on 2024-03-11 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('detail_text', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='todo_app.category')),
            ],
        ),
    ]
