# Generated by Django 5.0.6 on 2024-06-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
