# Generated by Django 5.0.6 on 2024-06-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_id',
            new_name='id',
        ),
    ]
